//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public int ServID { get; set; }
        public string CustFullName { get; set; }
        public string CustPhone { get; set; }
        public string LicenseNo { get; set; }
        public string ODOMeter { get; set; }
        public string OrderNumber { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal Quantity { get; set; }
        public decimal SubTotal { get; set; }
        public string VIN { get; set; }
        public string Operator { get; set; }
        public string CreatedOn { get; set; }
        public int ServCategoryID { get; set; }
    }
}
