//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineSales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransactionID { get; set; }
        public int ItemID { get; set; }
        public int TransactionTypeID { get; set; }
        public decimal Quantity { get; set; }
        public string Operator { get; set; }
        public string TransactionDate { get; set; }
    }
}
